name: Build and Deploy Next.js to Vercel

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger deployment when pull requests are opened to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the current GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (use the version required by your app)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Adjust the version according to your project

      # Step 3: Install dependencies using npm
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Next.js application
      - name: Build Next.js app
        run: npm run build

      # Step 5: Install Vercel CLI globally using npm
      - name: Install Vercel CLI
        run: npm install -g vercel

      # Step 6: Deploy to Vercel
      - name: Deploy to Vercel
        run: |
          vercel login ${{ secrets.VERCEL_TOKEN }}  # Login to Vercel using the token
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}  # Deploy to production
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # GitHub Secret containing your Vercel token
